from enum import StrEnum


class AssignmentErrorCode(StrEnum):
    ASSIGNMENT_NOT_FOUND = "ASSIGNMENT_NOT_FOUND"
    ASSIGNMENT_ALREADY_EXISTS = "ASSIGNMENT_ALREADY_EXISTS"
    ASSIGNMENT_IMMUTABLE = "ASSIGNMENT_IMMUTABLE"
    ASSIGNMENT_INVALID_TRANSITION = "ASSIGNMENT_INVALID_TRANSITION"
    ASSIGNMENT_CANNOT_BE_CANCELLED = "ASSIGNMENT_CANNOT_BE_CANCELLED"
    ASSIGNMENT_SHIFT_NOT_FOUND = "ASSIGNMENT_SHIFT_NOT_FOUND"
    ASSIGNMENT_DOCTOR_NOT_FOUND = "ASSIGNMENT_DOCTOR_NOT_FOUND"
    ASSIGNMENT_TIME_INVALID = "ASSIGNMENT_TIME_INVALID"
    ASSIGNMENT_OVERLAP = "ASSIGNMENT_OVERLAP"
