from enum import StrEnum


class DoctorErrorCode(StrEnum):
    DOCTOR_ALREADY_EXISTS = "DOCTOR_ALREADY_EXISTS"
    DOCTOR_NOT_FOUND = "DOCTOR_NOT_FOUND"
    DOCTOR_INACTIVE = "DOCTOR_INACTIVE"
    INVALID_CRM = "INVALID_CRM"
    INVALID_HOUR_RATE = "INVALID_HOUR_RATE"
    INVALID_NAME = "INVALID_NAME"
