from enum import StrEnum


class PeriodErrorCode(StrEnum):
    PERIOD_ALREADY_EXISTS = "PERIOD_ALREADY_EXISTS"
    PERIOD_NOT_FOUND = "PERIOD_NOT_FOUND"
    PERIOD_ALREADY_CLOSED = "PERIOD_ALREADY_CLOSED"
    PERIOD_ALREADY_PAID = "PERIOD_ALREADY_PAID"
    PERIOD_CANNOT_BE_REOPENED = "PERIOD_CANNOT_BE_REOPENED"
    PERIOD_IMMUTABLE = "PERIOD_IMMUTABLE"
    PERIOD_INVALID_STATUS_TRANSITION = "PERIOD_INVALID_STATUS_TRANSITION"
    PERIOD_INVALID_YEAR = "PERIOD_INVALID_YEAR"
    PERIOD_INVALID_MONTH = "PERIOD_INVALID_MONTH"
