from enum import StrEnum


class ShiftErrorCode(StrEnum):
    SHIFT_NOT_FOUND = "SHIFT_NOT_FOUND"
    SHIFT_ALREADY_EXISTS = "SHIFT_ALREADY_EXISTS"
    SHIFT_INACTIVE = "SHIFT_INACTIVE"
    SHIFT_IMMUTABLE = "SHIFT_IMMUTABLE"
    SHIFT_CANNOT_BE_CANCELLED = "SHIFT_CANNOT_BE_CANCELLED"
    SHIFT_ALREADY_STARTED = "SHIFT_ALREADY_STARTED"
    SHIFT_ALREADY_COMPLETED = "SHIFT_ALREADY_COMPLETED"
    SHIFT_INVALID_DATE = "SHIFT_INVALID_DATE"
    SHIFT_INVALID_TIME_RANGE = "SHIFT_INVALID_TIME_RANGE"
