from typing import Protocol, Optional

from app.models.period import Period


class PeriodRepositoryInterface(Protocol):
    def get_by_id(self, id: int) -> Optional[Period]: ...

    def get_by_year_month(self, year: int, month: int) -> Optional[Period]: ...

    def get_current_period(self) -> Optional[Period]: ...

    def exists_by_year_month(self, year: int, month: int, exclude_id: int | None = None) -> bool: ...

    def list(self, skip: int = 0, limit: int = 100) -> list[Period]: ...

    def search(
        self,
        skip: int = 0,
        limit: int = 100,
        sort_by: str = "id",
        sort_direction: str = "asc",
        **filters,
    ) -> list[Period]: ...

    def count_filtered(self, **filters) -> int: ...

    def create(self, entity: Period) -> Period: ...

    def update(self, entity: Period) -> Period: ...

    def exists(self, id: int) -> bool: ...

    def count(self) -> int: ...
