from typing import Protocol, TypeVar, Generic, Optional

T = TypeVar("T")


class IRepository(Protocol[T]):
    def get_by_id(self, id: int) -> Optional[T]: ...

    def list(self, skip: int = 0, limit: int = 100) -> list[T]: ...

    def create(self, entity: T) -> T: ...

    def update(self, entity: T) -> T: ...

    def delete(self, id: int) -> bool: ...

    def exists(self, id: int) -> bool: ...
